pages:
  fields:
    -
      handle: from
      field:
        display: From
        type: entries
        collections:
          - pages
          - campaigns
        max_items: 1
        mode: select
        width: 25
    -
      handle: to
      field:
        display: To
        type: entries
        collections:
          - pages
          - campaigns
        max_items: 1
        mode: select
        width: 25
    -
      handle: start_at
      field:
        display: Start
        mode: single
        type: date
        width: 25
        time_enabled: true
        icon: date
        time_seconds_enabled: false
        full_width: false
        inline: false
        columns: 1
        rows: 1
    -
      handle: end_at
      field:
        display: End
        mode: single
        type: date
        width: 25
        time_enabled: true
        icon: date
        time_seconds_enabled: false
        full_width: false
        inline: false
        columns: 1
        rows: 1
  display: Redirects
  type: grid
  mode: stacked
  add_row: 'Add Redirect'
